// Code generated by protoc-gen-js-fetch.
// DO NOT EDIT!

import * as apipb_datasetmodels from "./datasetmodels.pb";

export type DataInterval =  "HOURLY"  | "DAILY" ;
export const DataInterval_HOURLY: DataInterval = "HOURLY";
export const DataInterval_DAILY: DataInterval = "DAILY";

export class GamePlayingRequest {
  games: string[];
/**
From is the unix seconds time
*/
  from: string|number;
/**
To is the unix seconds time
*/
  to: string|number;
  interval: DataInterval;
}

export class GamePlayingReply {
  data: apipb_datasetmodels.DataSet;
}

export class SimplifiedReq {
  analysis: string;
/**
From is the unix seconds time
*/
  from: string|number;
/**
To is the unix seconds time
*/
  to: string|number;
  games: string[];
  interval: DataInterval;
}

