// Code generated by protoc-gen-js-fetch.
// DO NOT EDIT!

import * as apipb_messages from "./messages.pb";
import * as apipb_models from "./models.pb";
import * as google_protobuf_google_protobuf_field_mask from "./google/protobuf/field_mask.pb";

export type AddProfileActionConstraint =  "UNIQUE_KIND"  | "UNIQUE_KIND_IN_EDITIONS" ;
/**
There can be only single action with same kind in the profile
*/
export const AddProfileActionConstraint_UNIQUE_KIND: AddProfileActionConstraint = "UNIQUE_KIND";
/**
There can be only single action with same kind in edition of the profile
*/
export const AddProfileActionConstraint_UNIQUE_KIND_IN_EDITIONS: AddProfileActionConstraint = "UNIQUE_KIND_IN_EDITIONS";

export const ALL_AddProfileActionConstraint_VALUES: AddProfileActionConstraint[] = [AddProfileActionConstraint_UNIQUE_KIND,AddProfileActionConstraint_UNIQUE_KIND_IN_EDITIONS];

export interface StatisticsReq {
  timeFrom?: string|number;
  timeTo?: string|number;
}

export const StatisticsReq_timeFrom = "time_from";
export const StatisticsReq_timeTo = "time_to";
export interface StatisticsRes {
  statistics?: { [key: string]: string|number };
		}

export const StatisticsRes_statistics = "statistics";
export interface UpdateProfileReq {
  fields?: google_protobuf_google_protobuf_field_mask.FieldMask;
  profile?: apipb_models.Profile;
}

export const UpdateProfileReq_fields = "fields";
export const UpdateProfileReq_profile = "profile";
export interface UpdateChildReq {
  fields?: google_protobuf_google_protobuf_field_mask.FieldMask;
  child?: apipb_models.Child;
}

export const UpdateChildReq_fields = "fields";
export const UpdateChildReq_child = "child";
export interface UpdateProgressReq {
/**
number of stars earned by user
*/
  starsEarned?: number;
/**
put -1 to not update
*/
  newLevel?: number;
/**
put -1 in order not to update
*/
  levelStarCount?: number;
/**
Badges earned by user
*/
  badgesEarned?: apipb_models.Badge[];
  childId?: string;
}

export const UpdateProgressReq_starsEarned = "stars_earned";
export const UpdateProgressReq_newLevel = "new_level";
export const UpdateProgressReq_levelStarCount = "level_star_count";
export const UpdateProgressReq_badgesEarned = "badges_earned";
export const UpdateProgressReq_childId = "child_id";
export interface BatchUpdateChildrenReq {
  fields?: google_protobuf_google_protobuf_field_mask.FieldMask;
  child?: apipb_models.Child;
  ids?: string[];
}

export const BatchUpdateChildrenReq_fields = "fields";
export const BatchUpdateChildrenReq_child = "child";
export const BatchUpdateChildrenReq_ids = "ids";
export interface BatchUpdateChildrenRes {
  child?: apipb_models.Child[];
}

export const BatchUpdateChildrenRes_child = "child";
export interface AddProfileActionReq {
  profileId?: string;
  action?: apipb_models.ProfileAction;
  constraints?: AddProfileActionConstraint[];
}

export const AddProfileActionReq_profileId = "profile_id";
export const AddProfileActionReq_action = "action";
export const AddProfileActionReq_constraints = "constraints";
export interface ConsumeActionReq {
  profileId?: string;
  actionId?: string;
}

export const ConsumeActionReq_profileId = "profile_id";
export const ConsumeActionReq_actionId = "action_id";
